org: jhon1234
app: pdf-generate-walk-a-cise
service: pdf-generate-without-html-demo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

functions:
  pdf:
    handler: index.pdf
    events:
      - http:
          path: pdf
          method: get

plugins:
  - serverless-offline
  